#' Get Field Notes
#'
#' @param table Field notes are returned for the table named.  Tables are named using common names, not internal names -- attendance, contacts, etc.
#'
#' @return a data.frame containing the field notes for the desired table. The data.frame has one row for every field in the desired table.  The data.frame has four columns -- field_name, auto, action, notes
#' @export
#'
#' @examples
#' get_field_notes("members") # notes on the fields in the member table
get_field_notes <-function(table="attendance") {
    
    table_name=NULL
    
    field_data <- c(
        "attendance","assigned_user_id","no"," ","UUID of user/member owner of record",
        "attendance","contact_2_id","no"," ","UUID of person attending",
        "attendance","da_comments","no"," ","Comments on the attendance",
        "attendance","da_date_of_attendance","no"," ","Date of attendance",
        "attendance","da_social_event","no"," ","Social Event? 1=yes, 0=no",
        "attendance","da_time_in","no"," ","Date time person began attendance",
        "attendance","da_time_in_hour","no"," ","Hour person began attendance",
        "attendance","da_time_out","no"," ","Date time person ended attendance",
        "attendance","da_time_out_hour","no"," ","Hour person ended attendance",
        "attendance","location","no"," ","Location of attendance",
        "attendance","contact_id","unused","Unused","Unused",
        "attendance","description","unused","Unused","Unused",
        "attendance","group_activity_id","unused","Future","UUID of group activity",
        "attendance","created_by","yes"," ","UUID of person creating the record",
        "attendance","da_autoincrement","yes"," ","Auto generated record number",
        "attendance","da_reviewed","yes"," ","Reviewd? 1=yes, 0 = no",
        "attendance","da_total_hours","yes"," ","Auto-computed",
        "attendance","date_entered","yes"," ","Date the attendance record was created",
        "attendance","date_modified","yes"," ","Date the attendance record was modified",
        "attendance","deleted","yes"," ","1=deleted, 0=not deleted",
        "attendance","id","yes"," ","UUID of attendance record",
        "attendance","modified_user_id","yes"," ","UUID of user who last edited the record",
        "attendance","name","yes"," ","Auto generated name for record, eg. ATT-56663",
        "contacts","c2_contact_record_type_c","no"," ","Person, Family, Organization",
        "contacts","c2_groups","no"," ","Groups contacts belong to. e.g. Member, Rotary, Staff",
        "contacts","c2_primary_phone","no"," ","The phone we call first",
        "contacts","c2_salutation","no"," ","Words to follow Dear in a letter",
        "contacts","c2_secondary_phone","no"," ","The phone we call second",
        "contacts","contact2_applistic_number","no"," ","Legacy PersonID in Applistic person table",
        "contacts","contact2_full_name","no"," ","Name to appear on envelope",
        "contacts","contact2_nickname","no"," ","Preferred or nickname.  Eg: Mike, Jimbo, C.J.",
        "contacts","do_not_call","no"," ","1 for Solicit, 0 for do not solicit",
        "contacts","first_name","no"," ","Legal first name",
        "contacts","last_name","no"," ","Legal last name.  No suffix",
        "contacts","phone_home","no"," ","Home phone",
        "contacts","phone_mobile","no"," ","Mobile phone",
        "contacts","phone_other","no"," ","Other Phone",
        "contacts","phone_work","no"," ","Work Phone",
        "contacts","photo","no"," ","File or URL?",
        "contacts","primary_address_city","no"," ","City",
        "contacts","primary_address_country","no"," ","County",
        "contacts","primary_address_postalcode","no"," ","Zip Code",
        "contacts","primary_address_state","no"," ","State",
        "contacts","primary_address_street","no"," ","Street Address",
        "contacts","salutation","no"," ","Prefix, e.g. Dr., Mrs., Ms.",
        "contacts","c2_address_city","unused","Unused","Unused",
        "contacts","c2_address_country","unused","Unused","Unused",
        "contacts","c2_address_postalcode","unused","Unused","Unused",
        "contacts","c2_address_state","unused","Unused","Unused",
        "contacts","c2_address_street","unused","Unused","Unused",
        "contacts","c2_address_street_2","unused","Unused","Unused",
        "contacts","c2_address_street_3","unused","Unused","Unused",
        "contacts","description","unused","Unused","Unused",
        "contacts","email_address","unused","Unused","Unused",
        "contacts","member_id","unused","Unused","Unused",
        "contacts","c2_autoincrement","yes"," ","Auto incremented record number",
        "contacts","contact2_flourish_number","yes"," ","Auto record name.  eg. Contact-0152",
        "contacts","created_by","yes"," ","UUID of user who created the record",
        "contacts","date_entered","yes"," ","Date record was created",
        "contacts","date_modified","yes"," ","Date record was last edited",
        "contacts","deleted","yes"," ","1=deleted; 0 = not deleted",
        "contacts","id","yes"," ","UUID of the contact record",
        "contacts","modified_user_id","yes"," ","UUID of user who last edited the record",
        "employment","assigned_user_id","no","","UUID of user/member that owns record",
        "employment","contact_id","no","","UUID of Member employed",
        "employment","emp_assessment_date","no","","Date of employment assessment",
        "employment","emp_assessment_link","no","","URL of assessment",
        "employment","employer_id","no","","UUID of employer in contacts",
        "employment","flo_emp_approximate_hourly_pay","no","","Averqge Hourly Pay",
        "employment","flo_emp_approximate_hours_wk","no","","Average Hours worked per week",
        "employment","flo_emp_comments","no","","Comments on employment (not goal)",
        "employment","flo_emp_date_end","no","","Date employment ended",
        "employment","flo_emp_date_start","no","","Date employment started",
        "employment","flo_emp_job_description","no","","Job description",
        "employment","flo_emp_job_reason_ended","no","","Reason employment ended",
        "employment","flo_emp_job_title","no","","Job title",
        "employment","flo_emp_job_type","no","","Job support level",
        "employment","currency_id","unused","Unused","Unused",
        "employment","description","unused","Unused","Unused",
        "employment","flo_emp_employer_name","unused","Unused","Unused",
        "employment","created_by","yes","","UUID of user who created record",
        "employment","date_entered","yes","","Date record was created",
        "employment","date_modified","yes","","Last update date",
        "employment","deleted","yes","","1=yes, 0=no",
        "employment","employment_autoincrement","yes","","Auto-generated record number",
        "employment","id","yes","","UUID of record",
        "employment","modified_user_id","yes","","UUID of last editor",
        "employment","name","yes","","Auto generated record name, e.g. EMP-00012",
        "gifts","GOC_curator_comments","no","","Comments regarding the gift record",
        "gifts","GOC_gift_comments","no","","Comments by donor regarding gift",
        "gifts","GOC_restriction_letter","no","","URL of restriction letter",
        "gifts","assigned_user_id","no","","UUID of user/member owner of the record",
        "gifts","contact_2_id","no","","UUID of donor in contacts (sa_contact_2 table)",
        "gifts","deleted","no","","1=deleted, 0 = not deleted",
        "gifts","flo_anonymous_gift","no","","Restricted Gift. 1=yes,0=no",
        "gifts","flo_gift_amount","no","","Dollar amount of gift. Dollar value of in-kind gift.",
        "gifts","flo_gift_campaign","no","","Campaign. Eg. 2023 Amazing Give",
        "gifts","flo_gift_date","no","","Date Gift received by the GOC",
        "gifts","flo_gift_payment_method","no","","Payment Method. Eg. Cash, Check, PayPal",
        "gifts","flo_restricted_gift","no","","Anonymous. 1=yes,0=no",
        "gifts","flo_thank_you_date","no","","Date thank you was mailed or emailed by GOC",
        "gifts","description","unused","Unused","Unused",
        "gifts","gift_contact_id","unused","Unused","Unused",
        "gifts","created_by","yes","","UUID of user who created record",
        "gifts","date_entered","yes","","Date record created",
        "gifts","date_modified","yes","","Date record last updated",
        "gifts","gifts_autoincrement","yes","","Auto incremented record number",
        "gifts","id","yes","","UUID of gift record",
        "gifts","modified_user_id","yes","","UUID of user who last modified",
        "gifts","name","yes","","Auto generated record name, e.g., Gift-0113",
        "goals","assigned_user_id","no","","UUID of user/member record owner",
        "goals","contact_2_id","no","","UUID of staff goal writer",
        "goals","contact_id","no","","UUID of member for goals",
        "goals","flo_goal_action_plan","no","","Text describing steps to acheive goal",
        "goals","flo_goal_creation_date","no","","Date goal created",
        "goals","flo_goal_description","no","","Text describing goal",
        "goals","flo_goal_due_date","no","","Planned date for completion of goal",
        "goals","flo_goal_end_date","no","","Actual end of goal",
        "goals","flo_goal_needs","no","","Needs to complete the goal",
        "goals","flo_goal_other_support","no","","Other support needed to complete the goal",
        "goals","flo_goal_staff_support","no","","Staff support needed to complete the goal",
        "goals","flo_goal_start_date","no","","Goal start date",
        "goals","flo_goal_status","no","","Current status of the work to complete the goal",
        "goals","flo_goal_type","no","","Type of goal from pull down list",
        "goals","description","unused","Unused","Unused",
        "goals","created_by","yes","","UUID of record creator",
        "goals","date_entered","yes","","Date record created",
        "goals","date_modified","yes","","Date record last edited",
        "goals","deleted","yes","","1=deleted, 0=not deleted",
        "goals","goals_autoincrement","yes","","Auto incremented record number",
        "goals","id","yes","","UUID of the goal record",
        "goals","modified_user_id","yes","","UUID of the last editor of the goal",
        "goals","name","yes","","Auto generated record name, eg. goal-0788",
        "members","agency_id_c","no","","UUID of agency in sa_contacts_2",
        "members","assigned_user_id","no","","UUID of user/member owner of the record",
        "members","birthdate","no","","Date of birth of member",
        "members","contact_id_c","no","","UUID of coresponding record in sa_contacts_2",
        "members","deleted","no","","1=deleted, 0=not deleted",
        "members","do_not_call","no","","1=do not call, 0=okay to call",
        "members","emergency_address_city","no","","Emergency Contact City",
        "members","emergency_address_country","no","","Emergency Contact Country",
        "members","emergency_address_postalcode","no","","Emergency Contact Zip Code",
        "members","emergency_address_state","no","","Emergency Contact State",
        "members","emergency_address_street","no","","Emergency Contact Street Address",
        "members","first_name","no","","First Name of Member",
        "members","flo_accessibility_restrictions","no","","Multi-valued member accessibility restrictions",
        "members","flo_agency_comments","no","","Narrative from referring agency",
        "members","flo_allergies","no","","Multi-pick member allergies",
        "members","flo_annual_income","no","","Member monthly income categories",
        "members","flo_application_date","no","","Date of application",
        "members","flo_application_link","no","","URL of scanned application",
        "members","flo_approved_contact_methods_c","no","","Multi-pick, Member approved contact methods",
        "members","flo_considered_lgbt_c","no","","LGBTQ yes/no/unk",
        "members","flo_considered_veteran_c","no","","Veteran yes/no/unk",
        "members","flo_deceased_c","no","","Deceased yes/no/unk",
        "members","flo_degrees_certificates","no","","Muli-valued Member degrees and certificates",
        "members","flo_diagnoses_mult","no","","Multi-valued Member diagnose(s)",
        "members","flo_diagnosis_comments","no","","Comments regarding diagnoses",
        "members","flo_education_comments","no","","Comments/details regarding education",
        "members","flo_email_opt_out_c","no","","Member opt out of email Yes/No",
        "members","flo_emergency_con_phone_c","no","","Emergency contact phone",
        "members","flo_emergency_contact_c","no","","Emergency contact name",
        "members","flo_emergency_release","no","","Emrgency releaase of medical info? 1=yes, 0=no",
        "members","flo_employment_comments","no","","Comments regarding employment",
        "members","flo_ethnicity_hispanic_c","no","","Federal Hispanic Ethnicity",
        "members","flo_ever_employed","no","","Member ever employed? Yes/No/Unk",
        "members","flo_food_stamps","no","","Member receives food stamps (Yes/No/Unk)",
        "members","flo_gender_at_birth_c","no","","Member gender at birth",
        "members","flo_gender_identity_c","no","","Member current gender",
        "members","flo_highest_grade_completed","no","","Numerical grade. 12=hs, 16=college",
        "members","flo_housing_comments","no","","Comments regarding housing",
        "members","flo_housing_status_c","no","","Housing status from pick-list",
        "members","flo_housing_voucher","no","","Housing Voucher yes/no/unk",
        "members","flo_information_release","no","","Release info? 1=yes, 0 = no",
        "members","flo_mail_opt_out_c","no","","Opt out of email, Yes/No",
        "members","flo_marital_status_c","no","","Member marital status",
        "members","flo_media_release","no","","Use name in media 1=yes, 0=no",
        "members","flo_membership_status_c","no","","Member status, eg on leave",
        "members","flo_middle_name_c","no","","Member's middle name",
        "members","flo_nickname_preferred_name_c","no","","Member nickname",
        "members","flo_preferred_contact_methods","no","","Single value from pick list eg Phone",
        "members","flo_preferred_language_c","no","","Member preferred language",
        "members","flo_preferred_pronouns_c","no","","Member preferred pronouns",
        "members","flo_primary_language_c","no","","Member primary language",
        "members","flo_primary_phone","no","","This is the phone number we use on outreach reports and on View Member",
        "members","flo_race_mult","no","","Member race -- multiple",
        "members","flo_release_link","no","","URL of photo permissions document",
        "members","flo_resume_link","no","","URL of resume",
        "members","flo_secondary_language_c","no","","Member secondary language",
        "members","flo_secondary_phone","no","","A second phone we will use to contact Member",
        "members","flo_ssdi","no","","Member receives SSI (Yes/No/Unk)",
        "members","flo_ssi","no","","Members receives SSDI (Yes/No/Unk)",
        "members","flo_transportation_mode_c","no","","Member transportation mode",
        "members","goc_contact_id","no","","UUID of staff assigned to the Member",
        "members","last_name","no","","Legal last name of member",
        "members","phone_home","no","","Phone at residence",
        "members","phone_mobile","no","","Mobile phone",
        "members","phone_other","no","","Other phone",
        "members","phone_work","no","","Phone number at work",
        "members","primary_address_city","no","","Member Address -- city",
        "members","primary_address_country","no","","Member Address -- Country",
        "members","primary_address_postalcode","no","","Member Address -- Zip Code",
        "members","primary_address_state","no","","Member Address -- State",
        "members","primary_address_street","no","","Member Address -- Street",
        "members","referral_source_id_c","no","","UUID in sa_contacts_2 of agency making referral",
        "members","referral_type","no","","Pick-list, eg, self-referral",
        "members","referrer_id_c","no","","UUID in sa_contacts_2 of person making referral",
        "members","campaign_id","unused","Unused","Unused",
        "members","description","unused","Unused","Unused",
        "members","flo_billing_code_c","unused","Unused","Unused",
        "members","flo_contact_record_type_c","unused","Unused","All marked Member",
        "members","flo_external_id1_c","unused","Unused","Legacy Applistic ID",
        "members","flo_external_id2_c","unused","Unused","Unused",
        "members","flo_highest_level_of_educati_c","unused","Unused","Unused",
        "members","flo_last_employment","unused","Unused","Date of last employment (auto?)",
        "members","flo_phone_number_4_c","unused","Unused","Unused",
        "members","flo_phone_number_5_c","unused","Unused","Unused",
        "members","flo_preferred_phone_c","unused","Unused","Unused, see Primary",
        "members","flo_preferred_pronouns_dd","unused","Unused","Unused",
        "members","flo_race_c","unused","Unused","Unused",
        "members","flo_type_senior_citizen_c","unused","Unused","Unused",
        "members","flo_type_young_adults_c","unused","Unused","Unused",
        "members","flo_unit_chosen_by_member_c","unused","Unused","Unused",
        "members","member_address_city","unused","Unused","See Primary",
        "members","member_address_country","unused","Unused","See Primary",
        "members","member_address_postalcode","unused","Unused","See Primary",
        "members","member_address_state","unused","Unused","See Primary",
        "members","member_address_street","unused","Unused","See Primary",
        "members","member_address_street_2","unused","Unused","See Primary",
        "members","member_address_street_3","unused","Unused","See Primary",
        "members","photo","unused","Unused","Photo of Member",
        "members","portal_account_disabled","unused","Unused","Unused",
        "members","portal_user_type","unused","Unused","Unused",
        "members","refererr_id_c","unused","Unused","Misspelled.  Unused",
        "members","reports_to_id","unused","Unused","Unused",
        "members","salutation","unused","Unused","Pick-list: Mr, Ms., Mrs., etc",
        "members","age","yes","","Auto-computed from date of birth",
        "members","avg_time_at_ch","yes","","Auto-computed average time at clubhouse",
        "members","birthday_month","yes","","Auto-computed from date of birth",
        "members","contact_autoincrement","yes","","Auto-generated record number",
        "members","contact_flourish_number","yes","","Auto-generated record name, Eg. FlourishID-00245",
        "members","created_by","yes","","UUID of user creating the record",
        "members","date_entered","yes","","Date record was created",
        "members","date_modified","yes","","Date record was last edited",
        "members","id","yes","","UUID of member record",
        "members","last_attended","yes","","Auto-computed from attendance",
        "members","modified_user_id","yes","","UUID of user who last edited the record",
        "outreach","assigned_user_id","no","","UUID of user/member that owns record",
        "outreach","contact_id","no","","UUID of member being outreached",
        "outreach","person1_c","no","","UUID of person doing outreach",
        "outreach","person2_c","no","","UUID of second person doing outreach (if two people)",
        "outreach","ro_date_of_reach_out","no","","Date outreach was done",
        "outreach","ro_notes_from_reach_out","no","","Notes from the outreach",
        "outreach","ro_outcome_of_ro","no","","Pull-down value of outcome of outreach",
        "outreach","ro_type_of_reachout","no","","Method used.  Eg. phone",
        "outreach","contact_id_c","unused","Unused","Unused",
        "outreach","description","unused","Unused","Unused",
        "outreach","ro_is_it_billable","unused","Unused","Unused",
        "outreach","ro_primary_support_type","unused","Unused","Unused",
        "outreach","created_by","yes","","UUID of user that created the record",
        "outreach","date_entered","yes","","Date record created",
        "outreach","date_modified","yes","","Date record last edited",
        "outreach","deleted","yes","","1=deleted, 0=not deleted",
        "outreach","id","yes","","UUID of outreach record",
        "outreach","modified_user_id","yes","","UUID of user that last edited the record",
        "outreach","name","yes","","Auto generated name, eg. RO-0223",
        "outreach","ro_autoincrement","yes","","Auto numbering of records",
        "progress_notes","assigned_user_id","no","","UUID of user/member that owns record",
        "progress_notes","contact_2_id","no","","UUID of author of progress note",
        "progress_notes","contact_id","no","","UUID of member who is subject of note",
        "progress_notes","flo_date_of_note","no","","Date of progress note",
        "progress_notes","flo_note_end_date","no","","End date of period covered by the note",
        "progress_notes","flo_note_start_date","no","","Start date of period covered by the note",
        "progress_notes","goal_id","no","","UUID of goal for this progress note",
        "progress_notes","description","unused","Unused","Unused",
        "progress_notes","created_by","yes","","UUID of user who created record",
        "progress_notes","date_entered","yes","","Date record created",
        "progress_notes","date_modified","yes","","Date record last updated",
        "progress_notes","deleted","yes","","1=deleted, 0=not deleted",
        "progress_notes","id","yes","","UUID of the progress note record",
        "progress_notes","modified_user_id","yes","","UUID of user who last edited the progress note",
        "progress_notes","name","yes","","Auto generated record name, e.g. PN-9223",
        "progress_notes","pn_autoincrement","yes","","Auto generated record number",
        "progress_notes","progress_note","yes","","Text of the progress note",
        "supports","assigned_user_id","no","","UUID of user/member record owner",
        "supports","flo_support_date","no","","Date of support",
        "supports","flo_support_duration","no","","Duration of support in minutes",
        "supports","flo_support_note","no","","Text describing support",
        "supports","flo_support_type","no","","Type of support from pull-down, Eg: Culinary",
        "supports","sa_contacts_2_id","no","","UUID of staff member providing support",
        "supports","description","unused","Unused","Unused",
        "supports","created_by","yes","","UUID of record creator",
        "supports","date_entered","yes","","Date record was created",
        "supports","date_modified","yes","","Date record was last edited",
        "supports","deleted","yes","","1=deleted, 0=not deleted",
        "supports","id","yes","","UUID of support record",
        "supports","modified_user_id","yes","","UUID of record editor",
        "supports","name","yes","","Auto generated record name, Eg. S-00011",
        "supports","support_autoincrement","yes","","Auto incremented record number",
        "users","id","no","","?",
        "users","user_name","no","","?",
        "users","user_hash","no","","?",
        "users","system_generated_password","no","","?",
        "users","pwd_last_changed","no","","?",
        "users","authenticate_id","no","","?",
        "users","sugar_login","no","","?",
        "users","first_name","no","","?",
        "users","last_name","no","","?",
        "users","is_admin","no","","?",
        "users","external_auth_only","no","","?",
        "users","receive_notifications","no","","?",
        "users","description","no","","?",
        "users","date_entered","no","","?",
        "users","date_modified","no","","?",
        "users","modified_user_id","no","","?",
        "users","created_by","no","","?",
        "users","title","no","","?",
        "users","photo","no","","?",
        "users","department","no","","?",
        "users","phone_home","no","","?",
        "users","phone_mobile","no","","?",
        "users","phone_work","no","","?",
        "users","phone_other","no","","?",
        "users","phone_fax","no","","?",
        "users","status","no","","?",
        "users","address_street","no","","?",
        "users","address_city","no","","?",
        "users","address_state","no","","?",
        "users","address_country","no","","?",
        "users","address_postalcode","no","","?",
        "users","deleted","no","","?",
        "users","portal_only","no","","?",
        "users","show_on_employees","no","","?",
        "users","employee_status","no","","?",
        "users","messenger_id","no","","?",
        "users","messenger_type","no","","?",
        "users","reports_to_id","no","","?",
        "users","is_group","no","","?",
        "users","factor_auth","no","","?",
        "users","factor_auth_interface","no","","?"
    )

    field_notes <- data.frame(table_name = field_data[seq(1,length(field_data),5)],
                              field_name = field_data[seq(2,length(field_data),5)], 
                              auto= field_data[seq(3,length(field_data),5)], 
                              action = field_data[seq(4,length(field_data),5)], 
                              notes = field_data[seq(5,length(field_data),5)])
    
    subset(field_notes, table_name == table)[,-1]
}